const ASSET_CREATE_STEP_TYPES = {
  CONFIRM: "CONFIRM",
  INPUT: "INPUT",
};

const THEME_COLORS = {
  DANGER: "#FF0202",
  PRIMARY: "#664DE5",
  SECONDARY: "#5C6984",
  GREY: "#EAEEF5",
  BLACK: "#00000",
};

const BASIC_EDIT_LAYOUT_TYPES = { TOGGLE: "TOGGLE" };

module.exports = {
  ASSET_CREATE_STEP_TYPES,
  BASIC_EDIT_LAYOUT_TYPES,
  THEME_COLORS,
};
